/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from 'mongoose'

/**
 * Lean version of TaskDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TaskDocument.toObject()`. To avoid conflicts with model names, use the type alias `TaskObject`.
 * ```
 * const taskObject = task.toObject();
 * ```
 */
export type Task = {
  title: string
  description?: string
  status?: 'todo' | 'in-progress' | 'review' | 'done'
  priority?: 'low' | 'medium' | 'high'
  dueDate?: Date
  user: User['_id'] | User
  assignedTo?: User['_id'] | User
  teamId?: Team['_id'] | Team
  position?: number
  _id: mongoose.Types.ObjectId
  createdAt?: Date
  updatedAt?: Date
}

/**
 * Lean version of TaskDocument (type alias of `Task`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Task } from "../models"
 * import { TaskObject } from "../interfaces/mongoose.gen.ts"
 *
 * const taskObject: TaskObject = task.toObject();
 * ```
 */
export type TaskObject = Task

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TaskQuery = mongoose.Query<any, TaskDocument, TaskQueries> & TaskQueries

/**
 * Mongoose Query helper types
 *
 * This type represents `TaskSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TaskQueries = {}

export type TaskMethods = {}

export type TaskStatics = {}

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Task = mongoose.model<TaskDocument, TaskModel>("Task", TaskSchema);
 * ```
 */
export type TaskModel = mongoose.Model<TaskDocument, TaskQueries> & TaskStatics

/**
 * Mongoose Schema type
 *
 * Assign this type to new Task schema instances:
 * ```
 * const TaskSchema: TaskSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TaskSchema = mongoose.Schema<TaskDocument, TaskModel, TaskMethods, TaskQueries>

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Task = mongoose.model<TaskDocument, TaskModel>("Task", TaskSchema);
 * ```
 */
export type TaskDocument = mongoose.Document<mongoose.Types.ObjectId, TaskQueries> &
  TaskMethods & {
    title: string
    description?: string
    status?: 'todo' | 'in-progress' | 'review' | 'done'
    priority?: 'low' | 'medium' | 'high'
    dueDate?: Date
    user: UserDocument['_id'] | UserDocument
    assignedTo?: UserDocument['_id'] | UserDocument
    teamId?: TeamDocument['_id'] | TeamDocument
    position?: number
    _id: mongoose.Types.ObjectId
    createdAt?: Date
    updatedAt?: Date
  }

/**
 * Lean version of TeamDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `TeamDocument.toObject()`. To avoid conflicts with model names, use the type alias `TeamObject`.
 * ```
 * const teamObject = team.toObject();
 * ```
 */
export type Team = {
  name: string
  description?: string
  members: (User['_id'] | User)[]
  createdBy: User['_id'] | User
  _id: mongoose.Types.ObjectId
  createdAt?: Date
  updatedAt?: Date
}

/**
 * Lean version of TeamDocument (type alias of `Team`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Team } from "../models"
 * import { TeamObject } from "../interfaces/mongoose.gen.ts"
 *
 * const teamObject: TeamObject = team.toObject();
 * ```
 */
export type TeamObject = Team

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type TeamQuery = mongoose.Query<any, TeamDocument, TeamQueries> & TeamQueries

/**
 * Mongoose Query helper types
 *
 * This type represents `TeamSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type TeamQueries = {}

export type TeamMethods = {}

export type TeamStatics = {}

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Team = mongoose.model<TeamDocument, TeamModel>("Team", TeamSchema);
 * ```
 */
export type TeamModel = mongoose.Model<TeamDocument, TeamQueries> & TeamStatics

/**
 * Mongoose Schema type
 *
 * Assign this type to new Team schema instances:
 * ```
 * const TeamSchema: TeamSchema = new mongoose.Schema({ ... })
 * ```
 */
export type TeamSchema = mongoose.Schema<TeamDocument, TeamModel, TeamMethods, TeamQueries>

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Team = mongoose.model<TeamDocument, TeamModel>("Team", TeamSchema);
 * ```
 */
export type TeamDocument = mongoose.Document<mongoose.Types.ObjectId, TeamQueries> &
  TeamMethods & {
    name: string
    description?: string
    members: mongoose.Types.Array<UserDocument['_id'] | UserDocument>
    createdBy: UserDocument['_id'] | UserDocument
    _id: mongoose.Types.ObjectId
    createdAt?: Date
    updatedAt?: Date
  }

/**
 * Lean version of UserDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `UserDocument.toObject()`. To avoid conflicts with model names, use the type alias `UserObject`.
 * ```
 * const userObject = user.toObject();
 * ```
 */
export type User = {
  name: string
  email: string
  password: string
  role?: 'user' | 'admin'
  isValid?: boolean
  otp?: string
  otpExpires?: Date
  _id: mongoose.Types.ObjectId
  createdAt?: Date
  updatedAt?: Date
}

/**
 * Lean version of UserDocument (type alias of `User`)
 *
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { User } from "../models"
 * import { UserObject } from "../interfaces/mongoose.gen.ts"
 *
 * const userObject: UserObject = user.toObject();
 * ```
 */
export type UserObject = User

/**
 * Mongoose Query type
 *
 * This type is returned from query functions. For most use cases, you should not need to use this type explicitly.
 */
export type UserQuery = mongoose.Query<any, UserDocument, UserQueries> & UserQueries

/**
 * Mongoose Query helper types
 *
 * This type represents `UserSchema.query`. For most use cases, you should not need to use this type explicitly.
 */
export type UserQueries = {}

export type UserMethods = {
  correctPassword: (this: UserDocument, ...args: any[]) => any
  correctOTP: (this: UserDocument, ...args: any[]) => any
}

export type UserStatics = {}

/**
 * Mongoose Model type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserModel = mongoose.Model<UserDocument, UserQueries> & UserStatics

/**
 * Mongoose Schema type
 *
 * Assign this type to new User schema instances:
 * ```
 * const UserSchema: UserSchema = new mongoose.Schema({ ... })
 * ```
 */
export type UserSchema = mongoose.Schema<UserDocument, UserModel, UserMethods, UserQueries>

/**
 * Mongoose Document type
 *
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const User = mongoose.model<UserDocument, UserModel>("User", UserSchema);
 * ```
 */
export type UserDocument = mongoose.Document<mongoose.Types.ObjectId, UserQueries> &
  UserMethods & {
    name: string
    email: string
    password: string
    role?: 'user' | 'admin'
    isValid?: boolean
    otp?: string
    otpExpires?: Date
    _id: mongoose.Types.ObjectId
    createdAt?: Date
    updatedAt?: Date
  }

/**
 * Check if a property on a document is populated:
 * ```
 * import { IsPopulated } from "../interfaces/mongoose.gen.ts"
 *
 * if (IsPopulated<UserDocument["bestFriend"]>) { ... }
 * ```
 */
export function IsPopulated<T>(doc: T | mongoose.Types.ObjectId): doc is T {
  return doc instanceof mongoose.Document
}

/**
 * Helper type used by `PopulatedDocument`. Returns the parent property of a string
 * representing a nested property (i.e. `friend.user` -> `friend`)
 */
type ParentProperty<T> = T extends `${infer P}.${string}` ? P : never

/**
 * Helper type used by `PopulatedDocument`. Returns the child property of a string
 * representing a nested property (i.e. `friend.user` -> `user`).
 */
type ChildProperty<T> = T extends `${string}.${infer C}` ? C : never

/**
 * Helper type used by `PopulatedDocument`. Removes the `ObjectId` from the general union type generated
 * for ref documents (i.e. `mongoose.Types.ObjectId | UserDocument` -> `UserDocument`)
 */
type PopulatedProperty<Root, T extends keyof Root> = Omit<Root, T> & {
  [ref in T]: Root[T] extends mongoose.Types.Array<infer U>
    ? mongoose.Types.Array<Exclude<U, mongoose.Types.ObjectId>>
    : Exclude<Root[T], mongoose.Types.ObjectId>
}

/**
 * Populate properties on a document type:
 * ```
 * import { PopulatedDocument } from "../interfaces/mongoose.gen.ts"
 *
 * function example(user: PopulatedDocument<UserDocument, "bestFriend">) {
 *   console.log(user.bestFriend._id) // typescript knows this is populated
 * }
 * ```
 */
export type PopulatedDocument<DocType, T> = T extends keyof DocType
  ? PopulatedProperty<DocType, T>
  : ParentProperty<T> extends keyof DocType
  ? Omit<DocType, ParentProperty<T>> & {
      [ref in ParentProperty<T>]: DocType[ParentProperty<T>] extends mongoose.Types.Array<infer U>
        ? mongoose.Types.Array<
            ChildProperty<T> extends keyof U
              ? PopulatedProperty<U, ChildProperty<T>>
              : PopulatedDocument<U, ChildProperty<T>>
          >
        : ChildProperty<T> extends keyof DocType[ParentProperty<T>]
        ? PopulatedProperty<DocType[ParentProperty<T>], ChildProperty<T>>
        : PopulatedDocument<DocType[ParentProperty<T>], ChildProperty<T>>
    }
  : DocType

/**
 * Helper types used by the populate overloads
 */
type Unarray<T> = T extends Array<infer U> ? U : T
type Modify<T, R> = Omit<T, keyof R> & R

/**
 * Augment mongoose with Query.populate overloads
 */
declare module 'mongoose' {
  interface Query<ResultType, DocType, THelpers = {}> {
    populate<T extends string>(
      path: T,
      select?: string | any,
      model?: string | Model<any, THelpers>,
      match?: any
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers

    populate<T extends string>(
      options: Modify<PopulateOptions, { path: T }> | Array<PopulateOptions>
    ): Query<
      ResultType extends Array<DocType>
        ? Array<PopulatedDocument<Unarray<ResultType>, T>>
        : ResultType extends DocType
        ? PopulatedDocument<Unarray<ResultType>, T>
        : ResultType,
      DocType,
      THelpers
    > &
      THelpers
  }
}
